version: '3'

services:
  cronjob:
    build: ./cronjob
    user: "101:101" # uid/gid used by nginx image
    volumes:
      - ./www:/var/www/html
    # environment:
      # MAX_DISK_USAGE_PERCENTAGE: ""
      # DELETE_LAST_ACCESS: ""
      # DELETE_PERCENTAGE_INCREMENT: ""
      # DISCORD_WEBHOOK_URL: ""
  php:
    build: ./php
    user: "101:101" # uid/gid used by nginx image
    volumes:
      - ./www:/var/www/html
      - ./logs:/usr/local/log
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./www:/var/www/html
      - ./logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/includes:/etc/nginx/includes
    ports:
      - 80:8000
      - 443:4430
