version: '3'

services:
  php:
    image: php:7.4.23-fpm-bullseye
    user: "101:101" # uid/gid used by nginx image
    volumes:
      - ./www:/var/www/html
  nginx:
    image: nginx:1.20.1
    volumes:
      - ./www:/var/www/html
      - ./logs:/var/log/nginx
      - ./nginx/conf.d:/etc/nginx/conf.d
      - ./nginx/includes:/etc/nginx/includes
    ports:
      - 80:8000
      - 443:4430
