services:
  cronjob:
    build: ./cronjob
    user: "101:101" # uid/gid used by nginx image
    volumes:
      - ./www:/var/www/html
    # environment:
      # MAX_DISK_USAGE_PERCENTAGE: ""
      # DELETE_LAST_ACCESS: ""
      # DELETE_PERCENTAGE_INCREMENT: ""
      # DISCORD_WEBHOOK_URL: ""
    restart: unless-stopped
  php:
    build: ./php
    user: "101:101" # uid/gid used by nginx image
    volumes:
      - ./www:/var/www/html
    restart: unless-stopped
  nginx:
    build: ./nginx
    volumes:
      - ./www:/var/www/html
      - ./logs/nginx:/var/log/nginx
      - ./logs/supervisord:/var/log/supervisord
      - ./nginx/supervisord.conf:/etc/supervisord.conf:ro
      - ./nginx/conf.d:/etc/nginx/conf.d:ro
      - ./nginx/includes:/etc/nginx/includes:ro
    ports:
      - 80:8000
      - 443:4430
    restart: unless-stopped
