name: Docker Compose Build and Run Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Build Docker Compose services
      run: docker-compose build

    - name: Run Docker Compose services
      run: docker-compose up -d

    - name: Wait for containers to start
      run: sleep 10

    - name: Show container status
      run: docker-compose ps

    - name: Display nginx version
      run: docker-compose exec nginx printenv NGINX_VERSION

    - name: Display PHP version
      run: docker-compose exec php printenv PHP_VERSION

    - name: Check HTTP on port 80
      run: |
        RESPONSE=$(curl -fs http://localhost:80)
        echo "$RESPONSE" | grep -q "osu! download mirror" || (echo "Expected content not found on HTTP"; docker-compose logs && exit 1)

    - name: Tear down
      run: docker-compose down
