name: Docker Compose Build and Run Test

on:
  push:
    branches: [ "*" ]
  pull_request:
    branches: [ master ]

jobs:
  build-and-run:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Install docker-compose via apt
      run: |
        sudo apt update
        sudo apt install -y docker-compose

    - name: Display docker-compose version
      run: docker-compose --version

    - name: Build container images
      run: docker-compose build

    - name: Start containers
      run: docker-compose up -d

    - name: Allow some time for containers to start
      run: sleep 10

    - name: Show container status
      run: docker-compose ps

    - name: Display nginx version
      run: docker inspect osu-beatmap-mirror-docker-runtime_nginx_1 | jq -r '.[0].Config.Env[] | select(test("^NGINX_VERSION=")) | split("=")[1]'

    - name: Display PHP version
      run: docker inspect osu-beatmap-mirror-docker-runtime_php_1 | jq -r '.[0].Config.Env[] | select(test("^PHP_VERSION=")) | split("=")[1]'

    - name: Check HTTP on port 80
      run: |
        RESPONSE=$(curl -fs http://localhost:80)
        echo "$RESPONSE" | grep -q "osu! download mirror" || (echo "Expected content not found on HTTP"; docker-compose logs && exit 1)

    - name: Stop containers / tear down
      run: docker-compose down
